version: '3'

services:

  broker-service:
    build:
      context: ./broker
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  front-app:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 1
